name: Run tests

on: push

jobs:
  run-tests-and-report:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Add pCloudy jar
        run: mvn install:install-file -Dfile=lib/pCloudy-java-connector-11.0.7-jar-with-dependencies.jar -DgroupId=pCloudy-java-connector -DartifactId=pCloudy-java-connector -Dversion=11.0.7 -Dpackaging=jar

      - name: Install
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Generate report
        run: mvn allure:report